-- MySQL Script generated by MySQL Workbench
-- Tue Apr  7 12:49:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clients_book
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clients_book
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clients_book` DEFAULT CHARACTER SET utf8 ;
USE `clients_book` ;

-- -----------------------------------------------------
-- Table `clients_book`.`seasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clients_book`.`seasons` (
  `season_id` INT NOT NULL AUTO_INCREMENT,
  `season_name` VARCHAR(45) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`season_id`),
  UNIQUE INDEX `season_id_UNIQUE` (`season_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clients_book`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clients_book`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(100) NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clients_book`.`customer_summaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clients_book`.`customer_summaries` (
  `customer_id` INT NOT NULL,
  `season_id` INT NOT NULL,
  `total_repaid` DECIMAL NULL,
  `total_credit` DECIMAL NULL,
  INDEX `cs_ind1` (`customer_id` ASC),
  INDEX `cs_ind2` (`season_id` ASC),
  CONSTRAINT `cs_fk2`
    FOREIGN KEY (`season_id`)
    REFERENCES `clients_book`.`seasons` (`season_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cs_fk1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `clients_book`.`customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clients_book`.`repayment_uploads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clients_book`.`repayment_uploads` (
  `customer_id` INT NOT NULL,
  `season_id` INT NULL,
  `date` DATE NULL,
  `amount` DECIMAL NULL,
  INDEX `rap_innd1` (`customer_id` ASC) ,
  CONSTRAINT `rap_fk1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `clients_book`.`customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clients_book`.`repayments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clients_book`.`repayments` (
  `repayment_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `season_id` INT NOT NULL,
  `date` DATE NULL,
  `amount` DECIMAL NULL,
  `parent_id` INT NULL,
  PRIMARY KEY (`repayment_id`),
  UNIQUE INDEX `repayment_id_UNIQUE` (`repayment_id` ASC) ,
  INDEX `rep_ind1` (`customer_id` ASC),
  INDEX `rep_in2` (`season_id` ASC) ,
  CONSTRAINT `rep_fk1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `clients_book`.`customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `rep_fk2`
    FOREIGN KEY (`season_id`)
    REFERENCES `clients_book`.`seasons` (`season_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
